### ISSUE TITLE
ElementTree.fromstring broken in Python 3.8

### ISSUE THREAD

**Issue by endlisnis** [tiran/defusedxml#34]
I'm using pygal, which uses cairosvg, which uses defusedxml and I'm getting this error when I use "Python 3.8.0a3":
```Traceback (most recent call last):
  File "./alerts.py", line 1013, in <module>
    alert(alertTimeMarkers)
  File "/home/rolf/weather/alert.py", line 305, in __call__
    if self.call(sampleDay, alreadyReportedRecord) is not None:
  File "/home/rolf/weather/dailyRecordAlert.py", line 429, in call
    self.maybePostTweet(
  File "/home/rolf/weather/dailyRecordAlert.py", line 319, in maybePostTweet
    tweet, media = self.tweetText(
  File "/home/rolf/weather/dailyRecordAlert.py", line 123, in tweetText
    self.metarSnowChart(day, field=field, checkMax=recordIsMax) )
  File "/home/rolf/weather/dailyRecordAlert.py", line 47, in metarSnowChart
    return metarSnowChart.main(
  File "/home/rolf/weather/metarSnowChart.py", line 393, in main
    line_chart.render_to_png(fname,
  File "/usr/local/lib/python3.8/site-packages/pygal/graph/public.py", line 119, in render_to_png
    return cairosvg.svg2png(
  File "/usr/local/lib/python3.8/site-packages/cairosvg/__init__.py", line 66, in svg2png
    return surface.PNGSurface.convert(
  File "/usr/local/lib/python3.8/site-packages/cairosvg/surface.py", line 142, in convert
    tree = Tree(
  File "/usr/local/lib/python3.8/site-packages/cairosvg/parser.py", line 400, in __init__
    tree = ElementTree.fromstring(
  File "/usr/local/lib/python3.8/site-packages/defusedxml/common.py", line 113, in fromstring
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/usr/local/lib/python3.8/site-packages/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given
```

```
$ python3.8 -m pip freeze | grep def
defusedxml==0.5.0
```

I noticed that there is some funny business going on inside `ElementTree.py` where you are using some hidden functions.  Maybe they changed the signatures of those hidden functions?

**Comment by hroncok** [comment]
There are also test failures in Fedora 31 with python 3.8 (not yet in Fedora rawhide, but in Copr)

```
+ /usr/bin/python3 tests.py
EEEEEEEEEEEEEEEEEE................................
======================================================================
ERROR: test_allow_expansion (__main__.TestDefusedcElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 165, in test_allow_expansion
    self.parse(self.xml_bomb2, forbid_entities=False)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_dtd_forbidden (__main__.TestDefusedcElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 111, in test_dtd_forbidden
    self.assertRaises(DTDForbidden, self.parse, self.xml_bomb,
  File "/usr/lib64/python3.8/unittest/case.py", line 799, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib64/python3.8/unittest/case.py", line 214, in handle
    callable_obj(*args, **kwargs)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_dtd_with_external_ref (__main__.TestDefusedcElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 148, in test_dtd_with_external_ref
    self.parse(self.xml_dtd)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_entities_forbidden (__main__.TestDefusedcElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 87, in test_entities_forbidden
    self.assertRaises(EntitiesForbidden, self.parse, self.xml_bomb)
  File "/usr/lib64/python3.8/unittest/case.py", line 799, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib64/python3.8/unittest/case.py", line 214, in handle
    callable_obj(*args, **kwargs)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_entity_cycle (__main__.TestDefusedcElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 107, in test_entity_cycle
    self.assertRaises(self.cyclic_error, self.parse, self.xml_cyclic,
  File "/usr/lib64/python3.8/unittest/case.py", line 799, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib64/python3.8/unittest/case.py", line 214, in handle
    callable_obj(*args, **kwargs)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_external_file_ref (__main__.TestDefusedcElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 161, in test_external_file_ref
    self.assertRaises(self.external_ref_exception, self.parseString,
  File "/usr/lib64/python3.8/unittest/case.py", line 799, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib64/python3.8/unittest/case.py", line 214, in handle
    callable_obj(*args, **kwargs)
  File "tests.py", line 183, in parseString
    tree = self.module.fromstring(xmlstring, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 113, in fromstring
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_external_ref (__main__.TestDefusedcElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 151, in test_external_ref
    self.assertRaises(self.external_ref_exception, self.parse,
  File "/usr/lib64/python3.8/unittest/case.py", line 799, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib64/python3.8/unittest/case.py", line 214, in handle
    callable_obj(*args, **kwargs)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_simple_parse (__main__.TestDefusedcElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 75, in test_simple_parse
    self.parse(self.xml_simple)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_simple_parse_ns (__main__.TestDefusedcElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 81, in test_simple_parse_ns
    self.parse(self.xml_simple_ns)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_allow_expansion (__main__.TestDefusedElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 165, in test_allow_expansion
    self.parse(self.xml_bomb2, forbid_entities=False)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_dtd_forbidden (__main__.TestDefusedElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 111, in test_dtd_forbidden
    self.assertRaises(DTDForbidden, self.parse, self.xml_bomb,
  File "/usr/lib64/python3.8/unittest/case.py", line 799, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib64/python3.8/unittest/case.py", line 214, in handle
    callable_obj(*args, **kwargs)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_dtd_with_external_ref (__main__.TestDefusedElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 148, in test_dtd_with_external_ref
    self.parse(self.xml_dtd)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_entities_forbidden (__main__.TestDefusedElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 87, in test_entities_forbidden
    self.assertRaises(EntitiesForbidden, self.parse, self.xml_bomb)
  File "/usr/lib64/python3.8/unittest/case.py", line 799, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib64/python3.8/unittest/case.py", line 214, in handle
    callable_obj(*args, **kwargs)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_entity_cycle (__main__.TestDefusedElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 107, in test_entity_cycle
    self.assertRaises(self.cyclic_error, self.parse, self.xml_cyclic,
  File "/usr/lib64/python3.8/unittest/case.py", line 799, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib64/python3.8/unittest/case.py", line 214, in handle
    callable_obj(*args, **kwargs)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_external_file_ref (__main__.TestDefusedElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 161, in test_external_file_ref
    self.assertRaises(self.external_ref_exception, self.parseString,
  File "/usr/lib64/python3.8/unittest/case.py", line 799, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib64/python3.8/unittest/case.py", line 214, in handle
    callable_obj(*args, **kwargs)
  File "tests.py", line 183, in parseString
    tree = self.module.fromstring(xmlstring, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 113, in fromstring
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_external_ref (__main__.TestDefusedElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 151, in test_external_ref
    self.assertRaises(self.external_ref_exception, self.parse,
  File "/usr/lib64/python3.8/unittest/case.py", line 799, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib64/python3.8/unittest/case.py", line 214, in handle
    callable_obj(*args, **kwargs)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_simple_parse (__main__.TestDefusedElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 75, in test_simple_parse
    self.parse(self.xml_simple)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

======================================================================
ERROR: test_simple_parse_ns (__main__.TestDefusedElementTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 81, in test_simple_parse_ns
    self.parse(self.xml_simple_ns)
  File "tests.py", line 179, in parse
    tree = self.module.parse(xmlfile, **kwargs)
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/common.py", line 96, in parse
    parser = DefusedXMLParser(target=_TreeBuilder(),
  File "/builddir/build/BUILD/defusedxml-0.5.0/defusedxml/ElementTree.py", line 68, in __init__
    _XMLParser.__init__(self, html, target, encoding)
TypeError: __init__() takes 1 positional argument but 4 were given

----------------------------------------------------------------------
Ran 50 tests in 0.027s

FAILED (errors=18)
```

**Comment by hroncok** [comment]
https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.XMLParser

> Changed in version 3.8: Parameters are now keyword-only. The html argument no longer supported.

**Comment by hroncok** [comment]
https://github.com/tiran/defusedxml/pull/35

**Comment by endlisnis** [comment]
This resolves my issue.  Thanks.
