### ISSUE TITLE
defusedxml reads bytes, not str

### ISSUE THREAD

**Issue by timhemel** [tiran/defusedxml#85]
## Description

If I parse a file with defusedxml into an etree, and then try to write it, I get an error message:
```
TypeError: write() argument must be str, not bytes
```

I expect to see a serialized XML string.

My use case: I would like to parse an XML file with defusedxml and write it out without DTD etc, so that I can read it again with lxml, so that I can use its xpath function. I'm still trying to find out if that will work though.

## How to reproduce

Create a program `readwrite.py`:
```
from defusedxml.ElementTree import parse
import sys

t = parse(sys.argv[1])
t.write(sys.stdout)
```

Use the test input, `dtd.xml`:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head/>
    <body>text</body>
</html>
```

and run it:

```
$ python readwritexml.py dtd.xml
Traceback (most recent call last):
  File "readwritexml.py", line 5, in <module>
    t.write(sys.stdout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xml/etree/ElementTree.py", line 772, in write
    serialize(write, self._root, qnames, namespaces,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xml/etree/ElementTree.py", line 832, in _get_writer
    yield file.write
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 382, in _exit_wrapper
    callback(*args, **kwds)
TypeError: write() argument must be str, not bytes
```

My suspicion is that Python's ElementTree expects the data to be of type `str` and that defusedxml provides `bytes`.

**Comment by timhemel** [comment]
I've found a workaround:
```
from defusedxml import ElementTree as etree
import sys

with open(sys.argv[1],'r') as f:
    t = etree.fromstring(f.read())
    print(etree.tostring(t))
```

this results in:
```
$ python readwritexml.py dtd.xml
b'<html>\n    <head />\n    <body>text</body>\n</html>'
```

**Comment by tiran** [comment]
The code works as expected, see https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.ElementTree.write

> The output is either a [str](https://docs.python.org/3/library/stdtypes.html#str)ing (str) or binary ([bytes](https://docs.python.org/3/library/stdtypes.html#bytes)). This is controlled by the encoding argument. If encoding is "unicode", the output is a string; otherwise, it’s binary.

**Comment by timhemel** [comment]
Thanks for the quick response. My bad for not reading the docs thoroughly. Adding `encoding='unicode'` indeed works.
